# all-playbooks.yml

---
- name: play all playbooks that we prepared earlier
  import_playbook: yum-update.yml
  import_playbook: install-services.yml
  import_playbook: setup-app.yml
  import_playbook: setup-lb.yml