# check status-yml

---

- name: check the status of Apache
  hosts: webservers:loadbalancers
  become: true
  tasks:
  - name: Check the status of Apache
    command: service httpd status
    args:
      warn: no
    changed_when: false

  - name: this not fail
    command: /bin/false
    ignore_errors: yes