#collect-ec2-metadata-facts.yml
---
- name: Collecting metadata information
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/keys.yml
  tasks:
    - name: Change instances state by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: running
        instance_tags:
          Projet: Ansible
      register: ec2
    - name: Output IP Addresses of instances
      debug:
        msg: "IP address: {{ item.public_ip }}"
      loop: "{{ ec2.instances }}"

    - name: add host to inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: demogroup
        ansible_ssh_commmon_args: " -o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: /home/isow12/.ssh/ansible-key-pair.pem
      loop: "{{ec2.instances}}"

- name: second of collecting metadata information
  hosts: demogroup
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: Wait for SHH to come up
      wait_for_connection:
        delay: 5
        timeout: 90
    - name: Collect Instances facts
      ec2_metadata_facts:
      register: ec2_meta_facts

- name: stopping the instance
  hosts: localhost
  gather_facts: yes
  vars_files:
    - ../vars/keys.yml
  tasks:
    - name: Check out gathered facts
      debug:
        var: hostvars[groups['demogroup'][0]]['ansible_ec2_instance_id']

    - name: Stop instances state by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: stopped
        instance_tags:
          Projet: Ansible
      register: ec2