#deprovision-ec2.yml
---
- name: EC2 instance destroy
  hosts: localhost
  gather_facts: yes
  vars_files:
    - ../vars/keys.yml
  tasks:
    - name: Get Demo Instance
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: Demo-Ansible
      register: ec2_facts

    - name: Print Instance Ids
      debug: 
        var: ec2_facts.instances[0].instance_id
    
    - name: remove tags
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        resource: "{{ ec2_facts.instances[0].instance_id }}"
        tags:
          Name:
        state: absent

    - name: Terminate Instances
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: absent
        instance_id: 
          - "{{ ec2_facts.instances[0].instance_id }}"
      register: ec2         

    - name: Print out EC2 Items
      debug:
        var: ec2