#ec2-change-state.yml

---
- name: Change ec2 instances state by tag
  hosts: localhost
  gather_facts: yes
  vars_files:
    - ../vars/keys.yml
  tasks:
  - name: Stop ec2 instances by tag
    ec2: 
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      ec2_region: "{{ AWS_REGION }}"
      state: stopped
      instance_tags:
        Projet: Ansible