#setup-app.yml

---
- name: Set up the PHP application
  hosts: webservers
  become: true
  vars:
    path_to_app: "/var/www/html"

  vars_files:
    - ../vars/secret-variables.yml

  vars_prompt:
    - name: "upload_var"
      prompt: "Upload the index.php file ?"
    - name: "create_var"
      prompt: "Create info.php file"

  tasks:

  - name: Use Secret password here
    debug:
      msg: "{{ secret_password }}"

  - name: Upload application file
    copy:
      src: ../index.php
      dest: "{{path_to_app}}"
      mode: 0755
    when: upload_var == 'yes'
    tags: upload

  - name: Configure php.ini file
    lineinfile:
      path: /etc/php.ini
      regexp: ^short_open_tag
      line: 'short_open_tag=On'
    notify: restart apache

  - name: Create simple php application
    copy:
      dest: "{{path_to_app}}/info.php"
      content: "<h1> Info about Webserever {{ansible_hostname}} </h1>"
    when: create_var == 'yes'
    tags: create

  - name: See directory contents
    command: ls -ail {{path_to_app}}
    register: dir_contents

  - name: Debug directory contents
    debug:
      msg: "{{dir_contents}}"

  handlers:  
  - name: restart apache
    service: 
      name: httpd
      state: restarted
