# yum-update.yml
---

- name: Install Packages
  hosts: webservers:loadbalancers
  become: true
  
  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest